begin;

create table public.app_settings (
  key text primary key,
  value_json text not null,
  updated_at timestamptz not null default now()
);

create table public.work_days (
  work_date date primary key,
  notes text not null default '',
  focus_minutes integer not null default 0 check (focus_minutes >= 0),
  timer_duration_minutes integer not null default 25 check (timer_duration_minutes > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tasks (
  id text primary key,
  work_date date not null references public.work_days(work_date) on delete cascade,
  parent_task_id text references public.tasks(id) on delete restrict,
  title text not null,
  category text not null default '',
  priority text not null default 'medium' check (priority in ('high', 'medium', 'low')),
  due_date date not null,
  due_time time,
  estimate_minutes integer not null default 30 check (estimate_minutes >= 0),
  note text not null default '',
  status text not null default 'todo' check (status in ('todo', 'doing', 'done')),
  sort_order integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  completed_at timestamptz,
  created_by_user_id text,
  assignee_user_id text
);

create index idx_tasks_work_date on public.tasks(work_date);
create index idx_tasks_work_date_status on public.tasks(work_date, status);
create index idx_tasks_work_date_priority on public.tasks(work_date, priority);
create index idx_tasks_due_date_status on public.tasks(due_date, status);
create index idx_tasks_parent_task_id on public.tasks(parent_task_id);

create table public.task_assignees (
  task_id text not null references public.tasks(id) on delete cascade,
  user_id text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  primary key (task_id, user_id)
);

create index idx_task_assignees_user on public.task_assignees(user_id);
create index idx_task_assignees_task on public.task_assignees(task_id);

create table public.focus_sessions (
  id text primary key,
  work_date date not null references public.work_days(work_date) on delete cascade,
  duration_minutes integer not null check (duration_minutes > 0),
  started_at timestamptz,
  ended_at timestamptz,
  source text not null default 'timer' check (source in ('timer', 'manual', 'import')),
  created_at timestamptz not null default now()
);

create index idx_focus_sessions_work_date on public.focus_sessions(work_date);

create table public.notion_sync_runs (
  id bigint generated by default as identity primary key,
  synced_at timestamptz not null,
  source text not null default 'notion_webhook',
  root_page_url text not null,
  pages_scanned integer not null default 0,
  pages_changed integer not null default 0,
  status text not null default 'success' check (status in ('success', 'partial', 'failed')),
  error_message text
);

create index idx_notion_sync_runs_synced_at on public.notion_sync_runs(synced_at desc);

create table public.notion_pages_snapshot (
  page_url text primary key,
  title text not null,
  parent_title text,
  section_title text,
  content_hash text,
  fetched_at timestamptz,
  last_scanned_at timestamptz,
  last_event_type text,
  updated_at timestamptz not null default now()
);

create index idx_notion_pages_parent on public.notion_pages_snapshot(parent_title);
create index idx_notion_pages_section on public.notion_pages_snapshot(section_title);

create table public.notion_update_events (
  event_id text primary key,
  event_type text not null,
  page_url text not null,
  page_link text not null,
  title text not null,
  edited_at timestamptz,
  section_title text,
  parent_title text,
  editor_name text,
  summary text not null default '',
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  sync_run_id bigint references public.notion_sync_runs(id) on delete set null
);

create index idx_notion_update_events_page_url on public.notion_update_events(page_url);
create index idx_notion_update_events_received_at on public.notion_update_events(received_at desc);
create index idx_notion_update_events_sync_run on public.notion_update_events(sync_run_id);

create table public.github_sync_runs (
  id bigint generated by default as identity primary key,
  synced_at timestamptz not null,
  owner_name text not null,
  repos_scanned integer not null default 0,
  repos_changed integer not null default 0,
  commit_events_detected integer not null default 0,
  pr_events_detected integer not null default 0,
  status text not null default 'success' check (status in ('success', 'partial', 'failed')),
  error_message text
);

create index idx_github_sync_runs_synced_at on public.github_sync_runs(synced_at desc);

create table public.github_repo_snapshots (
  owner_name text not null,
  repo_name text not null,
  repo_url text not null,
  default_branch text not null,
  latest_commit_sha text,
  latest_commit_at timestamptz,
  open_pr_count integer not null default 0,
  last_scanned_at timestamptz not null,
  sync_run_id bigint references public.github_sync_runs(id) on delete set null,
  primary key (owner_name, repo_name)
);

create index idx_github_repo_snapshots_scanned_at on public.github_repo_snapshots(last_scanned_at desc);

create table public.github_pull_request_snapshots (
  owner_name text not null,
  repo_name text not null,
  pr_number integer not null,
  title text not null,
  state text not null,
  is_draft smallint not null default 0 check (is_draft in (0, 1)),
  updated_at timestamptz,
  pr_url text not null,
  base_branch text,
  head_branch text,
  head_sha text,
  author_name text,
  sync_run_id bigint references public.github_sync_runs(id) on delete set null,
  primary key (owner_name, repo_name, pr_number),
  foreign key (owner_name, repo_name)
    references public.github_repo_snapshots(owner_name, repo_name) on delete cascade
);

create index idx_github_pr_snapshots_updated_at on public.github_pull_request_snapshots(updated_at desc);

create table public.github_commit_events (
  owner_name text not null,
  repo_name text not null,
  commit_sha text not null,
  title text not null,
  commit_url text not null,
  occurred_at timestamptz,
  author_name text,
  status text not null default 'recent',
  summary text not null default '',
  sync_run_id bigint references public.github_sync_runs(id) on delete set null,
  primary key (owner_name, repo_name, commit_sha),
  foreign key (owner_name, repo_name)
    references public.github_repo_snapshots(owner_name, repo_name) on delete cascade
);

create index idx_github_commit_events_occurred_at on public.github_commit_events(occurred_at desc);

create table public.github_pr_events (
  event_uid text primary key,
  owner_name text not null,
  repo_name text not null,
  pr_number integer not null,
  event_kind text not null,
  title text not null,
  pr_url text not null,
  occurred_at timestamptz,
  author_name text,
  status text,
  summary text not null default '',
  sync_run_id bigint references public.github_sync_runs(id) on delete set null,
  foreign key (owner_name, repo_name)
    references public.github_repo_snapshots(owner_name, repo_name) on delete cascade
);

create index idx_github_pr_events_occurred_at on public.github_pr_events(occurred_at desc);
create index idx_github_pr_events_repo on public.github_pr_events(owner_name, repo_name, pr_number);

create table public.auth_sessions (
  id text primary key,
  user_id text not null,
  user_name text,
  email text,
  domain_id text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index idx_auth_sessions_expires_at on public.auth_sessions(expires_at);

create table public.auth_oauth_states (
  state text primary key,
  redirect_to text not null default '/',
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index idx_auth_oauth_states_expires_at on public.auth_oauth_states(expires_at);

create table public.line_works_messages (
  message_id text primary key,
  channel_id text not null,
  user_id text,
  domain_id text,
  content_type text not null,
  text text,
  issued_at timestamptz,
  raw_json text not null,
  received_at timestamptz not null default now()
);

create index idx_line_works_messages_channel_issued
  on public.line_works_messages(channel_id, issued_at desc);

create table public.line_works_attachments (
  id bigint generated by default as identity primary key,
  message_id text not null references public.line_works_messages(message_id) on delete cascade,
  file_id text not null,
  file_name text,
  file_size bigint,
  mime_type text,
  storage_bucket text not null,
  storage_path text not null,
  uploaded_at timestamptz not null default now()
);

create index idx_line_works_attachments_message on public.line_works_attachments(message_id);
create unique index idx_line_works_attachments_storage_path
  on public.line_works_attachments(storage_bucket, storage_path);

create table public.line_works_links (
  id bigint generated by default as identity primary key,
  message_id text not null references public.line_works_messages(message_id) on delete cascade,
  url text not null,
  found_at timestamptz not null default now()
);

create index idx_line_works_links_message on public.line_works_links(message_id);

create table public.line_works_link_previews (
  url text primary key,
  title text,
  description text,
  image_url text,
  site_name text,
  status text not null default 'success' check (status in ('success', 'failed')),
  error_message text,
  fetched_at timestamptz not null default now()
);

create index idx_line_works_link_previews_fetched on public.line_works_link_previews(fetched_at desc);

create table public.line_works_channels (
  channel_id text primary key,
  title text,
  channel_type text,
  user_id text,
  last_fetched_at timestamptz
);

create table public.user_last_seen (
  user_id text not null,
  source text not null,
  last_seen_at timestamptz not null,
  primary key (user_id, source)
);

create table public.user_notion_read (
  user_id text not null,
  event_id text not null,
  read_at timestamptz not null default now(),
  primary key (user_id, event_id)
);

create index idx_user_notion_read_user on public.user_notion_read(user_id, read_at desc);

create table public.users (
  user_id text primary key,
  user_name text,
  email text,
  domain_id text,
  last_login_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.task_references (
  id bigint generated by default as identity primary key,
  task_id text not null references public.tasks(id) on delete cascade,
  source text not null,
  external_id text not null,
  title text,
  excerpt text,
  external_url text,
  metadata_json text,
  created_at timestamptz not null default now(),
  created_by text
);

create index idx_task_references_task on public.task_references(task_id, created_at desc);
create index idx_task_references_source on public.task_references(source, external_id);
create unique index idx_task_references_dedupe on public.task_references(task_id, source, external_id);

create table public.site_links (
  id bigint generated by default as identity primary key,
  label text not null,
  url text not null,
  category text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_site_links_order on public.site_links(sort_order);
create index idx_site_links_category on public.site_links(category);

create table public.site_link_categories (
  name text primary key,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_site_link_categories_order on public.site_link_categories(sort_order, name);

insert into public.site_link_categories (name, sort_order)
values ('기타', 0)
on conflict (name) do nothing;

create table public.feed_events (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('notion', 'github', 'line-works')),
  created_at timestamptz not null default now()
);

create index idx_feed_events_created_at on public.feed_events(created_at desc);

create view public.v_today_task_summary with (security_invoker = true) as
select
  work_date,
  count(*)::integer as total_tasks,
  count(*) filter (where status = 'todo')::integer as todo_tasks,
  count(*) filter (where status = 'doing')::integer as doing_tasks,
  count(*) filter (where status = 'done')::integer as done_tasks,
  count(*) filter (where priority = 'high' and status <> 'done')::integer as open_high_priority_tasks,
  count(*) filter (where due_date < work_date and status <> 'done')::integer as overdue_tasks
from public.tasks
group by work_date;

create view public.v_github_repo_dashboard with (security_invoker = true) as
select
  s.owner_name,
  s.repo_name,
  s.repo_url,
  s.default_branch,
  s.latest_commit_sha,
  s.latest_commit_at,
  s.open_pr_count,
  count(e.commit_sha)::integer as tracked_commit_events
from public.github_repo_snapshots as s
left join public.github_commit_events as e
  on e.owner_name = s.owner_name and e.repo_name = s.repo_name
group by
  s.owner_name, s.repo_name, s.repo_url, s.default_branch,
  s.latest_commit_sha, s.latest_commit_at, s.open_pr_count;

insert into storage.buckets (id, name, public)
values ('work-tracking-private', 'work-tracking-private', false)
on conflict (id) do update set public = false;

revoke all on table
  public.app_settings,
  public.work_days,
  public.tasks,
  public.task_assignees,
  public.focus_sessions,
  public.notion_sync_runs,
  public.notion_pages_snapshot,
  public.notion_update_events,
  public.github_sync_runs,
  public.github_repo_snapshots,
  public.github_pull_request_snapshots,
  public.github_commit_events,
  public.github_pr_events,
  public.auth_sessions,
  public.auth_oauth_states,
  public.line_works_messages,
  public.line_works_attachments,
  public.line_works_links,
  public.line_works_link_previews,
  public.line_works_channels,
  public.user_last_seen,
  public.user_notion_read,
  public.users,
  public.task_references,
  public.site_links,
  public.site_link_categories,
  public.feed_events,
  public.v_today_task_summary,
  public.v_github_repo_dashboard
from anon, authenticated;

revoke all on sequence
  public.notion_sync_runs_id_seq,
  public.github_sync_runs_id_seq,
  public.line_works_attachments_id_seq,
  public.line_works_links_id_seq,
  public.task_references_id_seq,
  public.site_links_id_seq,
  public.feed_events_id_seq
from anon, authenticated;

do $$
declare
  target record;
begin
  for target in
    select schemaname, tablename
    from pg_tables
    where schemaname = 'public'
      and tablename in (
        'app_settings', 'work_days', 'tasks', 'task_assignees', 'focus_sessions',
        'notion_sync_runs', 'notion_pages_snapshot', 'notion_update_events',
        'github_sync_runs', 'github_repo_snapshots', 'github_pull_request_snapshots',
        'github_commit_events', 'github_pr_events', 'auth_sessions', 'auth_oauth_states',
        'line_works_messages', 'line_works_attachments', 'line_works_links',
        'line_works_link_previews', 'line_works_channels', 'user_last_seen',
        'user_notion_read', 'users', 'task_references', 'site_links',
        'site_link_categories', 'feed_events'
      )
  loop
    execute format('alter table %I.%I enable row level security', target.schemaname, target.tablename);
  end loop;
end;
$$;

commit;
